candy/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'CANDY'

# urlpatterns a lista de roteamentos de URLs para funções/Views
urlpatterns = [
    # GET /
    path('', views.voto_off, name='voto_off'),
    path('votee/<str:date>', views.voto_on, name='voto_on'),

]

webproject/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

urlpatterns = [

    path('', include('candy.urls', namespace='CANDY')),
    path('admin/', admin.site.urls),
]

webproject/models.py
from django.db import models

# Create your models here.
class voto(models.Model):
    VOTO_CHOICES = [
        ('DC', 'DOCE'),
        ('SL', 'SALGADO'),
    ]
    voto = models.CharField(max_length=2,choices=VOTO_CHOICES)

    def __str__(self):
        return self.voto

candy/views.py
from django.shortcuts import render

from webproject.models import voto

# Create your views here.
def voto_off(request):

    return render(request,'candy/novovoto.html',{})


def voto_on(request,date):
    #Se necessaio salvamos o novo dado!
    if(date == "DC"):
        print("DOCE")
        voto.objects.create(voto="DC")
    elif(date == "SL"):
        print("SALGADO")
        voto.objects.create(voto="SL")
    else:
        print("LIMPO")


    # Primeiro, buscamos os votos
    votos = voto.objects.all()

    # Incluímos no contexto
    contexto = {
        'salgados':voto.objects.filter(voto="SL").count(),
        'doces':voto.objects.filter(voto="DC").count(),
        'total':voto.objects.count()
    }

    return render(request,'candy/velhovoto.html',contexto)

candy/templates/candy/main.html
{% load static %}
<!doctype html>
<html lang="pt-br">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="icon" href="{% static 'icon/moon_icon.png' %}">

    <title>Django Website</title>

    <!-- Arrumar folhas de estilo (:-->
    <!-- Principal CSS do Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Estilos customizados para esse template -->
  </head>

  <body>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">Lua Azul</h5>
      <a class="btn btn-outline-primary" href="{% url 'CANDY:voto_off' %}">Votar</a>
    </div>

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">{% block titulo %}{% endblock %}</h1>
      <p class="lead">
          {% block subtitulo %}{% endblock %}
      </p>
    </div>

    <div class="container">
      <div class="card-deck mb-3 text-center">

        {% block doce %}

        {% endblock %}

        {% block ranking %}

        {% endblock %}

        {% block salgado %}

        {% endblock %}
      </div>

      <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
          <div class="col-12 col-md">
              <!--Icone da lua aqui-->
            <img class="mb-2" src="../../static/icon/moon_icon.png" alt="" width="24" height="24">

            <small class="d-block mb-3 text-muted">&copy; 2019</small>
          </div>

            <div class="col-6 col-md">
            <h5>Recomendaçao Django</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="https://docs.djangoproject.com/">Django</a></li>
              <li><a class="text-muted" href="https://tutorial.djangogirls.org/">Django Girls</a></li>
              <li><a class="text-muted" href="https://pythonacademy.com.br/">Python Academy</a></li>
            </ul>
          </div>

          <div class="col-6 col-md">
            <h5>Grupo</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Ashley Nascimento</a></li>
              <li><a class="text-muted" href="#">Cauan Siqueira</a></li>
              <li><a class="text-muted" href="#">Fábio Costa</a></li>
              <li><a class="text-muted" href="#">Hermany Vieira</a></li>
              <li><a class="text-muted" href="#">Marlon Dantas</a></li>
            </ul>
          </div>

            <div class="col-6 col-md">
            <h5>Codigo</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">GIT HUB</a></li>

            </ul>
          </div>
        </div>
      </footer>
    </div>


    <!-- Principal JavaScript do Bootstrap
    ================================================== -->
    <!-- Foi colocado no final para a página carregar mais rápido -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>

  </body>

</html>

candy/templates/candy/novovoto.html
{% extends 'candy/main.html' %}
{% load static %}


{% block titulo %}
    Pesquisa de interesse
{% endblock %}

{% block subtitulo %}
    Entre com seu Email e vote no seu favorito!
{% endblock %}

{% block doce %}
    <div class="card mb-4 shadow-sm">

          <div class="card-header">
            <h4 class="my-0 font-weight-normal">DOCE</h4>
          </div>

          <div class="card-body">

            <ul class="list-unstyled mt-3 mb-4">

              <li>
                <img src="{% static 'icon/brigadeiro.png' %}" alt="DOCE brigadeiro" class="img-thumbnail">
              </li>

            </ul>

{#            <h4  class="card-title pricing-card-title"><input type="email" placeholder="Email" name="email" required></h4>#}



            <a href="{% url 'CANDY:voto_on' date='DC' %}" type="button" class="btn btn-lg btn-block btn-primary">VOTE</a>

          </div>
        </div>
{% endblock %}

{% block ranking %}
{#    <div class="card mb-4 shadow-sm">#}
{##}
{#          <div class="card-header">#}
{#            <h4 class="my-0 font-weight-normal">RANKING</h4>#}
{#          </div>#}
{##}
{#          <div class="card-body">#}
{##}
{#            <div class="list-unstyled mt-3 mb-4">#}
{##}
{#            <a href="{% url 'CANDY:voto_on' %}" type="button" class="btn btn-lg btn-block btn-outline-primary ">MOSTAR</a>#}
{##}
{#            </div>#}
{#          </div>#}
{#    </div>#}
{% endblock %}

{% block salgado %}
            <div class="card mb-4 shadow-sm">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Salgado</h4>
          </div>
          <div class="card-body">

            <ul class="list-unstyled mt-3 mb-4">

              <li>
                <img src="{% static 'icon/coxinha.png' %}" alt="SALGADO Coxinha" class="img-thumbnail">
              </li>

            </ul>

{#            <h4  class="card-title pricing-card-title"><input type="email" placeholder="Email" name="email" required></h4>#}



            <a href="{% url 'CANDY:voto_on' date='SL' %}" type="button" class="btn btn-lg btn-block btn-primary">VOTE</a>

          </div>
        </div>
{% endblock %}

candy/templates/candy/velhovoto.html
{% extends 'candy/main.html' %}
{% load static %}


{% block titulo %}
    Resultados
{% endblock %}

{% block subtitulo %}
    Obrigado por vota!
{% endblock %}

{% block doce %}
    <div class="card mb-4 shadow-sm">

          <div class="card-header">
            <h4 class="my-0 font-weight-normal">DOCE</h4>
          </div>

          <div class="card-body">

            <h1 class="card-title pricing-card-title">{{ doces }} <small class="text-muted">/ {{ total }}</small></h1>

          </div>
        </div>
{% endblock %}

{% block ranking %}
    <div class="card mb-4 shadow-sm">

          <div class="card-header">
            <h4 class="my-0 font-weight-normal">RANKING</h4>
          </div>

          <div class="card-body">

            <div class="list-unstyled mt-3 mb-4">

            <a href="{% url 'CANDY:voto_off' %}" type="button" class="btn btn-lg btn-block btn-outline-primary ">Obrigado!</a>

            </div>
          </div>
    </div>
{% endblock %}

{% block salgado %}
            <div class="card mb-4 shadow-sm">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal">Salgado</h4>
          </div>
          <div class="card-body">

            <h1 class="card-title pricing-card-title">{{ salgados }} <small class="text-muted">/ {{ total }}</small></h1>

          </div>
        </div>
{% endblock %}